apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-config
  namespace: kube-system
data:
  cpi-vsphere.conf: |-
    [Global]
    insecure-flag = {{ .Values.vcenter.insecurehost | quote }}
    port = {{ .Values.vcenter.port | quote }}
    secret-name = "cpi-global-secret"
    secret-namespace = "kube-system"

    [VirtualCenter {{ .Values.vcenter.host | quote }}]
    datacenters = {{ .Values.vcenter.datacenter | quote }}
{{ if .Values.enableNsxt }}
    [NSXT]
    user = {{ .Values.nsxt.user }}
    password = {{ .Values.nsxt.password }}
    host = {{ .Values.nsxt.host }}
    insecure-flag = {{ .Values.nsxt.insecureFlag }}

    [LoadBalancer]
    ip-pool-name = {{ .Values.loadBalancer.ipPoolName }}
    size = {{ .Values.loadBalancer.size }}
    tier1-gateway-path = {{ .Values.loadBalancer.tier1GatewayPath }}
    tcp-app-profile-name = {{ .Values.loadBalancer.tcpAppProfileName | default "default-tcp-lb-app-profile" }}
    udp-app-profile-name = {{ .Values.loadBalancer.udpAppProfileName | default "default-udp-lb-app-profile" }}
{{ end }}
