apiVersion: v1
kind: Secret
metadata:
  name: vsphere-config-secret
  namespace: kube-system
type: Opaque
stringData:
  csi-vsphere.conf: |-
    [Global]
    cluster-id = "cluster-{{ randAlpha 5 | lower }}"
  
    [VirtualCenter {{ .Values.vcenter.host | quote }}]
    insecure-flag = {{ .Values.vcenter.insecurehost | quote }}
    user = {{ .Values.vcenter.username | quote }}
    password = {{ .Values.vcenter.password | quote }}
    port = {{ .Values.vcenter.port | quote }}
    datacenters = {{ .Values.vcenter.datacenter | quote }}

{{- if .Values.enableNsxt }}
    [NSXT]
    user = {{ .Values.nsxt.user }}
    password = {{ .Values.nsxt.password }}
    host = {{ .Values.nsxt.host }}
    insecure-flag = {{ .Values.nsxt.insecureFlag }}

    [LoadBalancer]
    ip-pool-name = {{ .Values.loadBalancer.ipPoolName }}
    size = {{ .Values.loadBalancer.size }}
    tier1-gateway-path = {{ .Values.loadBalancer.tier1GatewayPath }}
    tcp-app-profile-name = {{ .Values.loadBalancer.tcpAppProfileName | default "default-tcp-lb-app-profile" }}
    udp-app-profile-name = {{ .Values.loadBalancer.udpAppProfileName | default "default-udp-lb-app-profile" }}
{{- end }}